apiVersion: v2
name: ejbca
description: Official Keyfactor EJBCA Chart
type: application
version: "0.0.0"
appVersion: "0.0.0"
home: https://www.ejbca.org
icon: https://raw.githubusercontent.com/Keyfactor/ejbca-ce/main/.github/images/community-ejbca-icon.png
keywords: ["pki", "security", "encryption", "certificates", "management", "automation", "infrastructure", "pqc", "protocol", "tls"]
sources:
  - https://github.com/Keyfactor/ejbca-ce
  - https://docs.keyfactor.com/container/latest/ejbca
annotations:
  artifacthub.io/alternativeName: ejbca
  artifacthub.io/category: security
  artifacthub.io/license: LGPL-2.1+
  artifacthub.io/links: |
    - name: "Source"
      url: https://github.com/Keyfactor/ejbca-ce
    - name: "Documentation"
      url: https://docs.keyfactor.com/container/latest/ejbca
