# Default values for ejbca.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
ejbca:
  importEjbcaConfFiles: false
  #ejbcaConfFilesSecret: ejbca-conf

  ## mainly relevant for EJBCA peers(RA/VA)
  importExternalCas: false
  #externalCasSecret: managementca-secret

  configdumpImport:
    enabled: false
    initialize: false # Generate initial certificate for CAs on import (default: false)
    configMapName: # Option 1: Specify a ConfigMap containing your EJBCA ConfigDump JSON data
    configMapKey: # (Optional) The key in the ConfigMap where the EJBCA ConfigDump data is found (default: "configdump.json")
    inlineConfigdump: # Option 2: Directly insert your EJBCA ConfigDump JSON data here

  ## not recommended: applicable only when direct HTTP access to EJBCA is enabled
  importAppserverKeystore: false
  #appserverKeystoreSecret: keystore-secret
  importAppserverTruststore: false
  #appserverTruststoreSecret: truststore-secret

  ## only applicable for quick setup of ephemeral test environments
  #superadminPasswordOverride: "foo123"
  useEphemeralH2Database: false
  useH2Persistence: false
  #existingH2PersistenceClaim: "database-data-claim"
  env:
    TLS_SETUP_ENABLED: "later"
    # for ephemeral test environments and only applicable to CA node
    # TLS_SETUP_ENABLED: "simple"

    # database username and password are recommended to be input as secret
    # DATABASE_JDBC_URL: ""

    # Audit logging should only be enabled in CA node
    LOG_AUDIT_TO_DB: false
    # INFO, DEBUG, TRACE, ERROR
    LOG_LEVEL_APP: "INFO"
    LOG_LEVEL_SERVER: "INFO"

    # Debug the container scripts and wildfy traffic
    #DEBUG: full
    
    # Default Random Number Generator algorithm for certificate serial number generation.
    # Available algorithms are: BCSP800Hybrid, SHA1PRNG, default, defaultstrong
    EJBCA_RNGALGORITHM: "default"

    ## Observability
    # The IP address where port 8090 will listen for requests to /health, /health/ready,
    # /health/live and /metrics . Set this to 0.0.0.0 to bind to all container interfaces.
    OBSERVABLE_BIND: "127.0.0.1"
    # Set this to "true" to collect metrics and expose them at the /metrics endpoint for scraping.
    METRICS_ENABLED: false

    ## Global OCSP configurations
    OCSP_CHECK_SIGN_CERT_VALIDITY: true
    OCSP_NON_EXISTING_IS_GOOD: false

    ## SMTP configuration
    # Specify the FQDN or IP Address of the SMTP host for EJBCA to send email notifications.
    SMTP_DESTINATION: "localhost"
    SMTP_DESTINATION_PORT: "25"
    SMTP_FROM: no-reply@localhost
    SMTP_TLS_ENABLED: true
    # Used for Wildfly to connect using TLS to the SMTP server. This only supports public CA certificates.
    SMTP_SSL_ENABLED: true
    # The username used when authentication is required for SMTP server.
    SMTP_USERNAME: ejbca-mail
    # SMTP password should be given as secrets, see SMTP_PASSWORD secret in envRaw
    #SMTP_PASSWORD: ejbca

  #envRaw:
  #  - name: DATABASE_USER
  #    valueFrom:
  #     secretKeyRef:
  #       name: ejbcadbcredentials
  #       key: database_user
  #  - name: DATABASE_PASSWORD
  #    valueFrom:
  #     secretKeyRef:
  #       name: ejbcadbcredentials
  #       key: database_password
  #  - name: EJBCA_CLI_DEFAULTPASSWORD
  #    valueFrom:
  #     secretKeyRef:
  #       name: ejbca-confidentiality-secrets
  #       key: cli_default_password
  #  - name: SMTP_PASSWORD
  #    valueFrom:
  #     secretKeyRef:
  #       name: ejbca-smtp-secrets
  #       key: smtp_password
  # The PASSWORD_ENCRYPTION_KEY should be set for a production deployment of EJBCA
  #  - name: PASSWORD_ENCRYPTION_KEY
  #    valueFrom:
  #     secretKeyRef:
  #       name: ejbca-confidentiality-secrets
  #       key: password_encrpytion_key

  #envFrom:
  #  - secretRef:
  #      name: configdump-secrets

  # Extra init containers to be added to the deployment
  initContainers: []
  # Extra sidecar containers to be added to the deployment
  sidecarContainers: []
  # Extra volumes to be added to the deployment
  volumes: []
  # Extra volume mounts to be added to the deployment
  volumeMounts: []

hsm:
  # provide HSM container image here when keyfactor repository is not used i.e. 
  # company internal artifactory is used
  image:
  imagePullPolicy: IfNotPresent
  enabled: false
  softhsm:
    enabled: false
    logLevel: "INFO"
    tokenPersistentVolumeClaim: 
  luna:
    enabled: false
    server_name: "192.168.0.200"
    CKLOG2_ENABLED: 0
    PROTECTED_AUTHENTICATION_PATH_FLAG_STATUS: 0
    credentials:
      certificates:
        configMap: "hsm-luna-configmap"
        # mandatory keys for file mount: "server.pem", "dockerlunaclient.pem"
      privateKey:
        secret: "hsm-luna-secret-client-key"
        # mandatory key for file mount: "dockerlunaclientKey.pem"      
  utimaco:
    enabled: false
    hsmConfigurationSecret: ejbca-utimaco-configmap
      # mandatory keys for file mount: "cs_pkcs11_R3.cfg"
  nshield:
    enabled: false
    # configuration parameters provided as secret
    hsmConfigurationSecret: "nshield-secret"
    # mandatory keys for environment variables(example):
    # HSM_IP='192.168.34.101'
    # HSM_PORT='9004'
    # HSM_ESN='291F-03E0-8970'
    # HSM_HKNETI='dbbcb19108b208811dc2993ae7b8b878aee3f234'
    # RFS_IP='192.168.34.101'
    # RFS_PORT='9005'
    # RFS_MODE='readonly'

replicaCount: 1

# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
updateStrategy: {}
#  type: RollingUpdate
#  rollingUpdate: {}

image:
  # Application variant: not set for full EJBCA, "ra" or "va"
  #variant: ra
  repository: keyfactor/ejbca-ce
  tag: latest
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
podLabels: {}
podAnnotations: {}
podSecurityContext: {}
# fsGroup: 2000
# Annotations to add to the service EJBCA and nginx
serviceAnnotations: {}

securityContext: {}
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

# Only one of the following services can be enabled at a time
# Use this for ingress or reverse proxy outside of the EJBCA pod which may be connected to a LoadBalancer.
services:
  # recommended (automatically enabled when ingress is used)
  proxyHttp:
    enabled: false
    type: ClusterIP
    bindIP: 0.0.0.0
    httpPort: 8081
    httpsPort: 8082
  # recommended for Apache httpd reverse proxy
  proxyAJP:
    enabled: false
    type: ClusterIP
    bindIP: 0.0.0.0
    port: 8009
  # not recommended, should only be used for debugging purpose
  directHttp:
    enabled: false
    type: NodePort
    httpPort: 30080
    httpsPort: 30443
  # Extra sidecar ports to be added to the service, optionally used when sidecarContainers
  # are defined and need to expose ports
  sidecarPorts: []

# Recommended for cluster internal communications or external when LoadBalancer type is used to terminate TLS at the pod
nginx:
  image: nginx:1.27.1
  enabled: false
  initializeWithSelfSignedTls: false
  host: "ejbcahost"
  externalConfiguration:
  # Server TLS credential for cluster internal communication
  mountInternalNginxCert: false
  #secretInternalNginxCert: "internal-nginx-credential-secret-ca"
  service:
    type: ClusterIP
    bindIP: 0.0.0.0
    httpPort: 80
    httpsPort: 443
  # only relevant if multiple replicas
  loadBalancerAccess:
    enableStickySessionClientIp: false
    # create a load balancer service for each Pod with separate IP address
    enableReplicaSpecificAccess: false
  additionalHosts:
httpd:
  image: httpd:2.4
  enabled: false
  initializeWithSelfSignedTls: false
  host: "ejbca-node1.ejbca-pki"
  externalConfiguration:
  # Server TLS credential for cluster internal communication
  mountInternalHttpdCert: false
  secretInternalHttpdCert: "internal-httpd-credential-secret-ca"
  service:
    # Use LoadBalancer to terminate in the pod, otherwise use ClusterIP or NodePort
     type: ClusterIP
     bindIP: 0.0.0.0
     httpPort: 80
     httpsPort: 443
# External communication from cluster
# Requires services.proxyAJP or services.proxyHttp to be enabled for adminweb access
ingress:
  enabled: false
  className: "nginx"
  annotations:
    ## Do not redirect HTTP to HTTPS
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    ## Enable optional client certificate authentication
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "optional_no_ca"
    ## Secret containing trusted CA certificates. Use with auth-tls-verify-client: "on" or "optional"
    #nginx.ingress.kubernetes.io/auth-tls-secret: "default/managementca-secret"
    ## Pass client certificates to upstream server
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
    ## Verification depth of the client certificates chain
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
  hosts: []
  #- host: ""
  #  paths:
  #    - path: /ejbca
  #      pathType: Prefix
  tls: []
resources: {}
#limits:
#  cpu: "1"
#  memory: "2048Mi"
#requests:
#  cpu: 1000m
#  memory: "2048Mi"
# https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
  behavior: {}
  # scaleDown:
  #   stabilizationWindowSeconds: 300
  #   policies:
  #   - type: Percent
  #     value: 100
  #     periodSeconds: 15
  # scaleUp:
  #   stabilizationWindowSeconds: 0
  #   policies:
  #   - type: Percent
  #     value: 100
  #     periodSeconds: 15
  #   - type: Pods
  #     value: 4
  #     periodSeconds: 15
  #   selectPolicy: Max

# https://kubernetes.io/docs/tasks/run-application/configure-pdb/
podDisruptionBudget:
  create: false
  minAvailable: 1
  maxUnavailable: ""

# https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
nodeSelector: {}
affinity: {}

# https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
tolerations: []

# https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/
topologySpreadConstraints: []

# https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/
priorityClassName: ""

# https://kubernetes.io/docs/concepts/scheduling-eviction/kube-scheduler/
schedulerName: ""

# https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/
terminationGracePeriodSeconds: ""

# https://kubernetes.io/docs/concepts/services-networking/network-policies/
networkPolicy:
  # policyTypes:
  #   - Ingress
  #   - Egress
  #   ingress:
  #   - from:
  #       ...
  #   egress:
  #   - to:
  #       ...
    
