# Configuration for NGINX meant for cluster internal communication
{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ejbca.fullname" . }}-nginx-config
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
      access_log  /var/log/nginx/access.log  main;
      sendfile        on;
      keepalive_timeout  65;

      server {
        listen 80;

        server_name {{ .Values.nginx.host }};

        location / {
          proxy_pass http://{{ include "ejbca.fullname" . }}:8081;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
          proxy_set_header Host $host;
          proxy_http_version 1.1;
        }
      }

      server {
        listen 443 ssl;
        ssl_verify_client optional;

        server_name {{ .Values.nginx.host }};

        ssl_certificate /etc/nginx/ssl/pem/{{ .Values.nginx.host }}.pem;
        ssl_certificate_key /etc/nginx/ssl/pem/{{ .Values.nginx.host }}-Key.pem;
        ssl_client_certificate /etc/nginx/ssl/pem/{{ .Values.nginx.host }}-CA.pem;

        location / {
          proxy_pass http://{{ include "ejbca.fullname" . }}:8082;
          proxy_set_header SSL_CLIENT_CERT $ssl_client_cert;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_set_header Host $host;
          proxy_http_version 1.1;
        }
      }

    }
{{- end }}